### ISSUE TITLE
UNIQUE constraint failed for promises in large trace

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#42]
I ran the following R code:

[notes.txt](https://github.com/PRL-PRG/R-dyntrace/files/862435/notes.txt)

At first it ran OK, but after a few minutes (yes minutes) I started getting lots of:

`SQLite: [19] UNIQUE constraint failed: promises.id/UNIQUE constraint failed: promises.id in: insert into promises select 0x56327199f9f8;`

I think R might be re-using pointers for promises, so might have a problem.

In any case, the analysis is unreliable in the face of these errors.

**Comment by kondziu** [comment]
Here's the SQL with repeats.

[trace.sql.txt](https://github.com/PRL-PRG/R-dyntrace/files/862571/trace.sql.txt)

**Comment by nohajc** [comment]
I've made some progress on this. The ID generation and mapping to promise SEXP addresses is straightforward. We can use the promise pointers while the tracer is running because there are unique as long as the given promise is alive. When it gets garbage collected, we remove the corresponding record from the map (promise ptrs -> generated IDs) so that later, when another promise is created at the same address we can map it to a new ID.

Before I close the issue, however, I have to solve the problem with the first promise which is created at each call to Rdt (for the expression we are about to trace). It seems that it gets created before we setup our hooks, so when it is forced, we get its address but we don't have a generated ID for it.

**Comment by kondziu** [comment]
@nohajc  Can we ignore it? It's just noise.

**Comment by nohajc** [comment]
Actually, this was also an easy fix. I modified rdt_start to pass the promise of the traced expression into probe_begin. At probe_begin, I generate an ID for the promise (because it is referenced later when we force it) and put that into db as if the promise was allocated.
